<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
	'Access denied.' => 'Geen toegang',
	'Add' => 'Toevoegen',
	'Add child' => '',
	'Add {type}' => 'Voeg {type} toe',
	'Ancestors' => '',
	'Are you sure you want to delete this item?' => 'Weet je zeker dat je dit item wil verwijderen?',
	'Assign' => 'Toewijzen',
	'Assign permission' => 'Toegang toewijzen',
	'Assigned items' => 'Wijs items toe',
	'Assignments' => '',
	'Business rule' => '',
	'Cancel' => 'Annuleer',
	'Create' => 'Maak aan',
	'Delete' => 'Verwijder',
	'Data' => '',
	'Descendants' => '',
	'Description' => 'Omschrijving',
	'Edit' => 'Aanpassen',
	'Invalid request.' => '',
	'Item does not exist.' => 'Item bestaat niet',
	'Items' => '',
	'Items assigned to this user' => 'Items toegewezen aan deze gebruiker',
	'New {type}' => 'Nieuwe {type}',
	'No assignments found.' => '',
	'No {type} found.' => 'Geen {type} gevonden',
	'Page not found.' => 'Pagina niet gevonden',
	'Permissions' => '',
	'Permissions granted by this item' => '',
	'Permissions that inherit this item' => '',
	'Remove' => 'Verwijder',
	'Revoke' => 'Terugtrekken',
	'Save' => 'Opslaan',
	'Select item' => 'Selecteer item',
	'System name' => 'Systeemnaam',
	'System name cannot be changed after creation.' => 'Systeem naam kan niet gewijzigd worden na aanmaken',
	'This item does not have any ancestors.' => '',
	'This item does not have any descendants.' => '',
	'This user does not have any assignments.' => '',
	'Type' => '',
	'User' => 'gebruiker',
	'View' => 'Bekijken',
	'operation|operations' => 'Operatie|operaties',
	'role|roles' => 'Rol|rollen',
	'task|tasks' => 'Taak|taken',
);
